import pandas as pd
import numpy as np

'''
This script generates LaTeX tables summarizing the performance of the ceiling and maxlpt methods under different sensitivity analysis conditions 
(varying number of job types, machines, and budget multipliers).
It reads the results from CSV files generated by the sensitivity analysis, 
computes average runtimes, node counts, pruning rates, and counts of timeouts and zero-node cases for both methods.
The output is formatted as LaTeX tables that can be directly included in a research paper or report, 
providing a clear comparison of the two methods across the different experimental conditions.
The created tables are printed to the console, and can be copied into a LaTeX document for presentation.
'''





# Helper for pretty percent
percent = lambda x: f"{100*x:.1f}%" if not np.isnan(x) else "--"

# Jobs scaling
jobs_df = pd.read_csv("data/sensitivity_maxlpt_budget_20260219_125453/sensitivity_jobs_20260217_190717.csv")
for col in jobs_df.columns:
    jobs_df[col] = pd.to_numeric(jobs_df[col], errors='coerce')
jobs_grouped = jobs_df.groupby("n_jobs").agg(
    avg_runtime_ceiling=("ceiling_runtime", "mean"),
    avg_nodes_ceiling=("ceiling_nodes", "mean"),
    avg_pruning_ceiling=("ceiling_pruning_rate", "mean"),
    avg_runtime_maxlpt=("maxlpt_runtime", "mean"),
    avg_nodes_maxlpt=("maxlpt_nodes", "mean"),
    avg_pruning_maxlpt=("maxlpt_pruning_rate", "mean"),
    timeouts_ceiling=("ceiling_status", lambda x: sum(s != "success" for s in x)),
    timeouts_maxlpt=("maxlpt_status", lambda x: sum(s != "success" for s in x)),
    zero_nodes_ceiling=("ceiling_nodes", lambda x: sum(x == 0)),
    zero_nodes_maxlpt=("maxlpt_nodes", lambda x: sum(x == 0)),
)

print("\\begin{table}[htbp]")
print("\\centering")
print("\\caption{Performance scaling with number of job types (1h time limit)}")
print("\\label{tab:sensitivity-jobs}")
print("\\begin{tabular}{r|rrrrrrrrr}")
print("Job Types & Ceil Time & Ceil Nodes & Ceil Prune & Ceil 0 Nodes & MaxLPT Time & MaxLPT Nodes & MaxLPT Prune & MaxLPT 0 Nodes \\")
print("\\midrule")
for idx, row in jobs_grouped.iterrows():
    print(f"{int(idx)} & {row['avg_runtime_ceiling']:.2f} & {int(row['avg_nodes_ceiling'])} & {percent(row['avg_pruning_ceiling'])} & {int(row['zero_nodes_ceiling'])} & {row['avg_runtime_maxlpt']:.2f} & {int(row['avg_nodes_maxlpt'])} & {percent(row['avg_pruning_maxlpt'])} & {int(row['zero_nodes_maxlpt'])} \\")
print("\\bottomrule\n\\end{tabular}\n\\end{table}")

# Repeat for machines and budget
machines_df = pd.read_csv("data/sensitivity_maxlpt_budget_20260219_125453/sensitivity_machines.csv")
machines_grouped = machines_df.groupby("m_machines").agg(
    avg_runtime_ceiling=("ceiling_runtime", "mean"),
    avg_nodes_ceiling=("ceiling_nodes", "mean"),
    avg_pruning_ceiling=("ceiling_pruning_rate", "mean"),
    avg_runtime_maxlpt=("maxlpt_runtime", "mean"),
    avg_nodes_maxlpt=("maxlpt_nodes", "mean"),
    avg_pruning_maxlpt=("maxlpt_pruning_rate", "mean"),
    timeouts_ceiling=("ceiling_status", lambda x: sum(s != "success" for s in x)),
    timeouts_maxlpt=("maxlpt_status", lambda x: sum(s != "success" for s in x)),
    zero_nodes_ceiling=("ceiling_nodes", lambda x: sum(x == 0)),
    zero_nodes_maxlpt=("maxlpt_nodes", lambda x: sum(x == 0)),
)

print("\n\n\\begin{table}[htbp]")
print("\\centering")
print("\\caption{Performance scaling with number of machines (1h time limit)}")
print("\\label{tab:sensitivity-machines}")
print("\\begin{tabular}{r|rrrrrrrrr}")
print("Machines & Ceil Time & Ceil Nodes & Ceil Prune & Ceil 0 Nodes & MaxLPT Time & MaxLPT Nodes & MaxLPT Prune & MaxLPT 0 Nodes \\")
print("\\midrule")
for idx, row in machines_grouped.iterrows():
    print(f"{int(idx)} & {row['avg_runtime_ceiling']:.2f} & {int(row['avg_nodes_ceiling'])} & {percent(row['avg_pruning_ceiling'])} & {int(row['zero_nodes_ceiling'])} & {row['avg_runtime_maxlpt']:.2f} & {int(row['avg_nodes_maxlpt'])} & {percent(row['avg_pruning_maxlpt'])} & {int(row['zero_nodes_maxlpt'])} \\")
print("\\bottomrule\n\\end{tabular}\n\\end{table}")

budget_df = pd.read_csv("data/sensitivity_maxlpt_budget_20260219_125453/sensitivity_budget.csv")
budget_grouped = budget_df.groupby("budget_multiplier").agg(
    avg_runtime_ceiling=("ceiling_runtime", "mean"),
    avg_nodes_ceiling=("ceiling_nodes", "mean"),
    avg_pruning_ceiling=("ceiling_pruning_rate", "mean"),
    avg_runtime_maxlpt=("maxlpt_runtime", "mean"),
    avg_nodes_maxlpt=("maxlpt_nodes", "mean"),
    avg_pruning_maxlpt=("maxlpt_pruning_rate", "mean"),
    timeouts_ceiling=("ceiling_status", lambda x: sum(s != "success" for s in x)),
    timeouts_maxlpt=("maxlpt_status", lambda x: sum(s != "success" for s in x)),
    zero_nodes_ceiling=("ceiling_nodes", lambda x: sum(x == 0)),
    zero_nodes_maxlpt=("maxlpt_nodes", lambda x: sum(x == 0)),
)

print("\n\n\\begin{table}[htbp]")
print("\\centering")
print("\\caption{Performance scaling with budget multiplier (1h time limit)}")
print("\\label{tab:sensitivity-budget}")
print("\\begin{tabular}{r|rrrrrrrrr}")
print("Multiplier & Ceil Time & Ceil Nodes & Ceil Prune & Ceil 0 Nodes & MaxLPT Time & MaxLPT Nodes & MaxLPT Prune & MaxLPT 0 Nodes \\")
print("\\midrule")
for idx, row in budget_grouped.iterrows():
    print(f"{idx:.2f} & {row['avg_runtime_ceiling']:.2f} & {int(row['avg_nodes_ceiling'])} & {percent(row['avg_pruning_ceiling'])} & {int(row['zero_nodes_ceiling'])} & {row['avg_runtime_maxlpt']:.2f} & {int(row['avg_nodes_maxlpt'])} & {percent(row['avg_pruning_maxlpt'])} & {int(row['zero_nodes_maxlpt'])} \\")
print("\\bottomrule\n\\end{tabular}\n\\end{table}")
